function p = setup_KMtoolbox()
%PATHDEF Search path defaults.
%   PATHDEF returns a string that can be used as input to MATLABPATH
%   in order to set the path.

  
%   Copyright 1984-2007 The MathWorks, Inc.
%   $Revision: 1.4.2.2 $ $Date: 2007/06/07 14:45:14 $


% DO NOT MODIFY THIS FILE.  IT IS AN AUTOGENERATED FILE.  
% EDITING MAY CAUSE THE FILE TO BECOME UNREADABLE TO 
% THE PATHTOOL AND THE INSTALLER.

p = path;

% Determine where your m-file's folder is.
folder = fileparts(which('setup_KMtoolbox.m')); 
% locate the ./src folder and add it to the path
src_folder = genpath([folder,'/src/']);
p = [src_folder,p];

path(p);